### ISSUE TITLE
SBT 0.13 version does not exist

### ISSUE THREAD

**Issue by wsargent** [cb372/sbt-explicit-dependencies#8]
This looks like it is only available for sbt 1.0.  Using `0.13.16` I get:

```
[info] Loading global plugins from /Users/wsargent/dotfiles/sbt/.sbt/0.13/plugins
[info] Loading project definition from /Users/wsargent/work/ucp-modules/project/project
[info] Loading project definition from /Users/wsargent/work/ucp-modules/project
[info] Updating {file:/Users/wsargent/work/ucp-modules/project/}ucp-modules-build...
[info] Resolving com.github.cb372#sbt-explicit-dependencies;0.2.1 ...
[warn] 	module not found: com.github.cb372#sbt-explicit-dependencies;0.2.1
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.github.cb372/sbt-explicit-dependencies/scala_2.10/sbt_0.13/0.2.1/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.github.cb372/sbt-explicit-dependencies/scala_2.10/sbt_0.13/0.2.1/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /Users/wsargent/.ivy2/local/com.github.cb372/sbt-explicit-dependencies/scala_2.10/sbt_0.13/0.2.1/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/github/cb372/sbt-explicit-dependencies_2.10_0.13/0.2.1/sbt-explicit-dependencies-0.2.1.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /Users/wsargent/.sbt/preloaded/com.github.cb372/sbt-explicit-dependencies/0.2.1/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////Users/wsargent/.sbt/preloaded/com/github/cb372/sbt-explicit-dependencies_2.10_0.13/0.2.1/sbt-explicit-dependencies-0.2.1.pom
[warn] ==== com-mvn: tried
[warn]   https://repo.lightbend.com/commercial-releases/com/github/cb372/sbt-explicit-dependencies_2.10_0.13/0.2.1/sbt-explicit-dependencies-0.2.1.pom
[warn] ==== com-ivy: tried
[warn]   https://repo.lightbend.com/commercial-releases/com.github.cb372/sbt-explicit-dependencies/scala_2.10/sbt_0.13/0.2.1/ivys/ivy.xml
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.github.cb372#sbt-explicit-dependencies;0.2.1: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.github.cb372:sbt-explicit-dependencies:0.2.1 (scalaVersion=2.10, sbtVersion=0.13)
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.github.cb372:sbt-explicit-dependencies:0.2.1 (scalaVersion=2.10, sbtVersion=0.13) (/Users/wsargent/work/ucp-modules/project/plugins.sbt#L28-29)
[warn] 		  +- default:ucp-modules-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: com.github.cb372#sbt-explicit-dependencies;0.2.1: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
```

**Comment by cb372** [comment]
I’ve never written a cross-built sbt plugin before. Sounds like a good opportunity to learn how to do so!

**Comment by wsargent** [comment]
So it's a couple of things, 

```
// Run with ^compile / ^publishLocal for cross-sbt compilation
crossSbtVersions := Seq("0.13.16", "1.0.3")
```

and then if you're using sbt release, https://github.com/sbt/sbt-release/issues/206

```
sbtrelease.ReleasePlugin.autoImport.releaseCrossBuild := false

// release settings (need to enable sbt crossbuilding publish)
import ReleaseTransformations._
releaseProcess := Seq[ReleaseStep](
  checkSnapshotDependencies,
  inquireVersions,
  runClean,
  //releaseStepCommandAndRemaining("^ test"),
  setReleaseVersion,
  commitReleaseVersion,
  tagRelease,
  releaseStepCommandAndRemaining("^ publish"),
  setNextVersion,
  commitNextVersion,
  pushChanges
)
```
